### PR TITLE
swap "compare active file with clipboard"

### LINKED ISSUE #23: Swap for Comparing File with Clipboard
I'd like to be able to swap diff views between a file and the clipboard

Steps taken:
1. I have an open file
2. I have some content in my clipboard
3. Run `File: Compare Active File with Clipboard`
4. Run `Swap diff documents`
5. I get `Nothing to swap :(`

The use case I have here is I have chatGPT helping me with writing small scripts, and as I get it to output different versions of the code I want to make sure it isn't making modifications elsewhere where I don't see them. Currently, this works but the new version - which is in my clipboard - is displayed on the left pane and I want it on the right pane

### PR DESCRIPTION
**Pull request by j4k0xb**
Closes #23, I've also needed that feature so many times

The scheme format is defined in https://github.com/microsoft/vscode/blob/3aea4d643c8a2849d2d676ab619d81c83f8395b5/src/vs/workbench/contrib/files/browser/fileActions.ts#L813

### CODE REVIEW

**Comment by shalimski** [comment]
It's not that simple. I've tried this approach, it doesn't work. The file with clipboardCompare extension doesn't really exist.

**Comment by j4k0xb** [comment]
how does it not work? on the first swap it created a new tab `foo - Untitled-1` (tbh would be better if it showed `Clipboard`)
and when swapping again it opens the original diff tab
image

same behavior as with 2 real files

**Comment by shalimski** [comment]
1. Open file
3. run "Compare Active File with Clipboard"
image
image
4. run "Swap diff documents"
5. got error
image

os: ubuntu 23.04
vscode: 1.81.1

**Comment by j4k0xb** [comment]
Ah I see. The error only happens when `Close Previous Diff` is enabled because it disposes the clipboard document but then tries to use it afterwards

**Comment by j4k0xb** [comment]
Fixed everything now I think:

- `Close Previous Diff` no longer errors, now the old tab gets closed after showing the diff
- Tab label gets swapped: 
image
image

The different tab handling also (unintentionally) provided some other benefits:
- Works with multiple opened diff tabs by choosing the active one, no `More than 2 visible files, cant swap it :(` message anymore
- Independent of the scheme, would prevent future issues like #3 and #10

**Comment by shalimski** [comment]
Great! @j4k0xb thanks!

**Pull request merged**
